"""create initial schema

Revision ID: c7ef2ee489ec
Revises: 
Create Date: 2026-06-25 08:17:03.975442
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'c7ef2ee489ec'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('id', sa.CHAR(36), nullable=False),
    sa.Column('kid', sa.String(length=64), nullable=False),
    sa.Column('algorithm', sa.String(length=10), nullable=False),
    sa.Column('scope', sa.JSON(), nullable=True),
    sa.Column('secret', sa.Text(), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('key_holder_account_id', sa.CHAR(36), nullable=False),
    sa.Column('key_holder_account_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_api_keys')),
    sa.UniqueConstraint('kid', name=op.f('uq_api_keys_kid'))
    )
    op.create_index('ix_api_keys_key_holder', 'api_keys', ['key_holder_account_id', 'key_holder_account_type'], unique=False)
    op.create_table('levels',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_levels')),
    sa.UniqueConstraint('key', 'value', name='uq_levels_key_value')
    )
    op.create_table('permissions',
    sa.Column('id', sa.CHAR(36), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('verb', sa.String(length=10), nullable=False),
    sa.Column('path', sa.String(length=255), nullable=False),
    sa.Column('action', sa.String(length=10), nullable=False),
    sa.Column('topic', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_permissions'))
    )
    op.create_index('ix_permissions_role', 'permissions', ['role'], unique=False)
    op.create_table('restrictions',
    sa.Column('id', sa.CHAR(36), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('scope', sa.String(length=20), nullable=False),
    sa.Column('value', sa.String(length=64), nullable=False),
    sa.Column('code', sa.Integer(), nullable=True),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_restrictions'))
    )
    op.create_index('ix_restrictions_scope_value', 'restrictions', ['scope', 'value'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.CHAR(36), nullable=False),
    sa.Column('uid', sa.String(length=32), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_digest', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('otp', sa.Boolean(), nullable=False),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.Column('referral_id', sa.CHAR(36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['referral_id'], ['users.id'], name=op.f('fk_users_referral_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email')),
    sa.UniqueConstraint('uid', name=op.f('uq_users_uid')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username'))
    )
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_state'), 'users', ['state'], unique=False)
    op.create_table('activities',
    sa.Column('id', sa.CHAR(36), nullable=False),
    sa.Column('user_id', sa.CHAR(36), nullable=True),
    sa.Column('target_uid', sa.String(length=32), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('user_ip', sa.String(length=45), nullable=True),
    sa.Column('user_ip_country', sa.String(length=2), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('topic', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('result', sa.String(length=20), nullable=False),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_activities_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_activities'))
    )
    op.create_index('ix_activities_created_at', 'activities', ['created_at'], unique=False)
    op.create_index(op.f('ix_activities_topic'), 'activities', ['topic'], unique=False)
    op.create_index(op.f('ix_activities_user_id'), 'activities', ['user_id'], unique=False)
    op.create_table('comments',
    sa.Column('id', sa.CHAR(36), nullable=False),
    sa.Column('user_id', sa.CHAR(36), nullable=False),
    sa.Column('author_uid', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('data', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_comments_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_comments'))
    )
    op.create_index(op.f('ix_comments_user_id'), 'comments', ['user_id'], unique=False)
    op.create_table('data_storages',
    sa.Column('id', sa.CHAR(36), nullable=False),
    sa.Column('user_id', sa.CHAR(36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('data', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_data_storages_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_data_storages')),
    sa.UniqueConstraint('user_id', 'title', name='uq_data_storages_user_id_title')
    )
    op.create_index(op.f('ix_data_storages_user_id'), 'data_storages', ['user_id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.CHAR(36), nullable=False),
    sa.Column('user_id', sa.CHAR(36), nullable=False),
    sa.Column('doc_type', sa.String(length=50), nullable=False),
    sa.Column('doc_number', sa.Text(), nullable=False),
    sa.Column('doc_number_index', sa.String(length=64), nullable=False),
    sa.Column('upload', sa.String(length=255), nullable=True),
    sa.Column('doc_expire', sa.Date(), nullable=True),
    sa.Column('identificator', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_documents_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documents'))
    )
    op.create_index('ix_documents_doc_number_index', 'documents', ['doc_number_index'], unique=False)
    op.create_index(op.f('ix_documents_user_id'), 'documents', ['user_id'], unique=False)
    op.create_table('labels',
    sa.Column('id', sa.CHAR(36), nullable=False),
    sa.Column('user_id', sa.CHAR(36), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('scope', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_labels_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_labels')),
    sa.UniqueConstraint('user_id', 'key', 'scope', name='uq_labels_user_id_key_scope')
    )
    op.create_index('ix_labels_key_value', 'labels', ['key', 'value'], unique=False)
    op.create_index(op.f('ix_labels_user_id'), 'labels', ['user_id'], unique=False)
    op.create_table('phones',
    sa.Column('id', sa.CHAR(36), nullable=False),
    sa.Column('user_id', sa.CHAR(36), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('number', sa.Text(), nullable=False),
    sa.Column('number_index', sa.String(length=64), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=True),
    sa.Column('validated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_phones_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_phones'))
    )
    op.create_index('ix_phones_number_index', 'phones', ['number_index'], unique=False)
    op.create_index(op.f('ix_phones_user_id'), 'phones', ['user_id'], unique=False)
    op.create_table('profiles',
    sa.Column('id', sa.CHAR(36), nullable=False),
    sa.Column('user_id', sa.CHAR(36), nullable=False),
    sa.Column('first_name', sa.Text(), nullable=True),
    sa.Column('last_name', sa.Text(), nullable=True),
    sa.Column('dob', sa.Text(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.Text(), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('state', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_profiles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_profiles'))
    )
    op.create_index(op.f('ix_profiles_user_id'), 'profiles', ['user_id'], unique=False)
    op.create_table('service_accounts',
    sa.Column('id', sa.CHAR(36), nullable=False),
    sa.Column('uid', sa.String(length=32), nullable=False),
    sa.Column('owner_id', sa.CHAR(36), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_service_accounts_owner_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_service_accounts')),
    sa.UniqueConstraint('email', name=op.f('uq_service_accounts_email')),
    sa.UniqueConstraint('uid', name=op.f('uq_service_accounts_uid'))
    )
    op.create_index(op.f('ix_service_accounts_owner_id'), 'service_accounts', ['owner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # Drop tables in reverse dependency order. Each drop_table also removes the
    # table's indexes and foreign keys; dropping an FK-backing index explicitly
    # first fails on MySQL (error 1553), so it is done this way deliberately.
    op.drop_table("service_accounts")
    op.drop_table("profiles")
    op.drop_table("phones")
    op.drop_table("labels")
    op.drop_table("documents")
    op.drop_table("data_storages")
    op.drop_table("comments")
    op.drop_table("activities")
    op.drop_table("users")
    op.drop_table("restrictions")
    op.drop_table("permissions")
    op.drop_table("levels")
    op.drop_table("api_keys")
