"""add user otp secret

Revision ID: d914f8f7c658
Revises: c7ef2ee489ec
Create Date: 2026-06-25 12:42:52.916132
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'd914f8f7c658'
down_revision: str | None = 'c7ef2ee489ec'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('otp_secret', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'otp_secret')
    # ### end Alembic commands ###
